### PR TITLE
Base desktop-gadget on stable upstream gadget

### PR DESCRIPTION
**Pull request by xnox**
Drop support for rebuilding this gadget with brandstore support.

Drop building this gadget from scratch. As doing this requires to ensure this gadget is not released to stable ahead of matching snapd & kernel snaps. Instead stage stable gadget to always acquire stable bootloader artefacts. This is because the primary changes in this gadget are w.r.t. device settings.

### CODE REVIEW

**Review by jhenstridge — COMMENTED** [review]
My main concerns with this change are:

1. With the current method of managing the gadget, we get to see any conflicts in the gadget.yaml when we merge from upstream. This seems like it would make it harder to reconcile changes.
2. This also seems like it removes our ability to decide when to do merges: if a new stable version of the upstream gadget is pushed out, we need to make sure our gadget works with those changes before we can make any changes of our own.

If we were only adding files and changing the snap's base, this seems like it'd be a much better way to manage the snap. But the fact we're modifying files makes it seem more fragile.

**Comment by xnox** [comment]
1. History remains shared, thus you can and should continue to merge changes. This remains the same.

2. Currently git repository tip is being merged, which is edge code often incompatible with stable kernel snaps and stable snapd. Yet this gadget is being released to stable without coordination with kernel/snapd/core teams or what is referenced in the model. Thus there is already risk missmatch right now. In theory this gadget should merge gadget.yaml changes equivalent to the released stable channel.

3. However it is safe to stay on older boot loader artefacts, behind what is shipped in edge by parent gadget. As foundations and kernel teams provide forward compatibility (use stable bootloader with edge kernel) but not backwards compatibility (using edge bootloader with stable kernel)

4. If there is filenames missmatch and gadget.yaml Vs stable stage gadget - this gadget build will fail either build or review tools. Making build time protections still the same.

5. If future remodel to/from classic gadget is desired care should be taken to make this and classic gadgets compatible in disk layouts. I am not sure if this has been considered.

Overall this change reduces risk of shipping unstable gadget that bricks machines, or revokes active kernels during key rotation event. Given that currently edge bootloader is shipped relative stable kernel.

**Comment by jhenstridge** [comment]
If any of the files this PR deletes changes, we'll see a merge conflict. That makes reviewing changes almost useless.

With that said, the nature of our gadget.yaml changes are fairly restricted:

1. greatly increase the size of the `ubuntu-seed` partition to cover the additional desktop snaps.
2. change some snap settings with `defaults:`
3. connect some plugs/slots with `connections:`

So perhaps we could just merge those changes into the the upstream gadget.yaml during build rather than maintaining a fork of the file. With that, all that remains would be files we don't need to worry about merging (the cloud-init and splash screen changes).

**Comment by xnox** [comment]
> If any of the files this PR deletes changes, we'll see a merge conflict. That makes reviewing changes almost useless.
> 
> With that said, the nature of our gadget.yaml changes are fairly restricted:
> 
> 1. greatly increase the size of the `ubuntu-seed` partition to cover the additional desktop snaps.
> 2. change some snap settings with `defaults:`
> 3. connect some plugs/slots with `connections:`
> 
> So perhaps we could just merge those changes into the the upstream gadget.yaml during build rather than maintaining a fork of the file. With that, all that remains would be files we don't need to worry about merging (the cloud-init and splash screen changes).

Yes, progmatically parsing/patching gadget.yaml with like yq or python yaml module might express the intent of your changes in a more structured way. And yes changes to deleted files is pain to review on GitHub as one cannot set remote merge strategy to keep-ours aka assume still deleted.

I don't have time to proposed that unfortunately.

About seed size change - I wonder if we could bump it to the same size on either classic-pc or pc gadgets. To allow the two to be compatible with each other for potential future remodels or reinstalls.

**Pull request closed without merging**
